### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [xp-bar/zsh-bar-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

**Comment by xp-bar** [comment]
Oh wow! I haven't checked this in months, that's my bad - will do!

**Comment by xp-bar** [comment]
Done. Cheers mate!

**Comment by unixorn** [comment]
Thanks! Added in https://github.com/unixorn/awesome-zsh-plugins/pull/702 - can you add on a license too while you're working on this? If you haven't already decided on one,  I recommend [choosealicense.com](https://choosealicense.com).

**Comment by xp-bar** [comment]
Added in [a86eef374a83d8349aa58d4d7036599b53426940](https://github.com/xp-bar/zsh-bar-theme/commit/a86eef374a83d8349aa58d4d7036599b53426940). Cheers!
